version: "3.9"

services:
  app:
    build:
      context: . # current directory
      args:
        - DEV=true
    ports:
      - "8000:8000" # expose port 8000 to the host
    volumes:
      - ./app:/app # mount the app directory to the container
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
